---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-counter
  namespace: raz-test-one
  labels:
    app: visit-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visit-counter
  template:
    metadata:
      labels:
        app: visit-counter
    spec:
      containers:
      - name: visit-counter
        image: "razvanmoj/redis-checker:t11"
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: raz-test-one-ec-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: visit-counter
  namespace: raz-test-one
spec:
  type: ClusterIP
  selector:
    app: visit-counter
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
